name: AiPi-helloworld 云编译

on: 
  repository_dispatch:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update && sudo apt-get full-upgrade -y && sudo apt-get upgrade -y && sudo apt-get autoremove -y
        sudo apt-get install make gcc vim cmake git ninja-build -y
        sudo apt-get install autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev -y
    - name: Clone source code and Build Firmware
      run: |
        cd /opt
        git clone https://github.com/Ai-Thinker-Open/AiPi-Open-Kits.git
        cd AiPi-Open-Kits
        git submodule init
        git submodule update
        cd aithinker_Ai-M6X_SDK
        . install.sh
        . export.sh
        cd examples
        cd helloworld
        make
        cd build/
        zip -r AiPi-helloworld-build_out.zip ./build_out/
#    - name : Upload packages
#      uses: actions/upload-artifact@main
#      if: always()
#      with:
#        name: AiPi-helloworld 
#        path: /opt/AiPi-Open-Kits/aithinker_Ai-M6X_SDK/examples/helloworld/build/AiPi-helloworld-build_out.zip
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        files: /opt/AiPi-Open-Kits/aithinker_Ai-M6X_SDK/examples/helloworld/build/AiPi-helloworld-build_out.zip
