name: AiPi-helloworld 云编译

on: 
  repository_dispatch:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update && sudo apt-get full-upgrade -y && sudo apt-get upgrade -y && sudo apt-get autoremove -y
        sudo apt-get install make gcc vim cmake git ninja-build -y
        sudo apt-get install autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev -y
    - name: Clone source code and Build Firmware
      run: |
        cd /opt
        git clone https://github.com/Ai-Thinker-Open/AiPi-Open-Kits.git
        cd AiPi-Open-Kits
        git submodule init
        git submodule update
        cd aithinker_Ai-M6X_SDK
        . install.sh
        . export.sh
        cd examples
        cd helloworld
        make
        cd /opt/AiPi-Open-Kits/aithinker_Ai-M6X_SDK/examples/helloworld/build/build_out/
        zip AiPi-helloworld.zip helloworld_bl616.bin.ota helloworld_bl616.bin.xz.ota helloworld_bl616.bin.xz
    - name : Upload packages
      uses: actions/upload-artifact@main
      if: always()
      with:
        name: AiPi-helloworld 
        path: /opt/AiPi-Open-Kits/aithinker_Ai-M6X_SDK/examples/helloworld/build/build_out/AiPi-helloworld.zip
